name: Python application

on: [push, pull_request]

jobs:
  tests_python:
    name: Test on Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Cache pip
      uses: actions/cache@v4
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libproj-dev libgeos-dev gdal-bin libgdal-dev libsqlite3-mod-spatialite
        python -m pip install --upgrade pip
        python -m pip install --upgrade 'tox>=4.0.0rc3'

    - name: Run tox targets for ${{ matrix.python_version }}
      run: tox run -f py$(echo ${{ matrix.python_version }} | tr -d .)
